name: Self-update
on:
  push:
    branches: [ main ]
 # schedule:
#    - cron: "0 13 * * *" # every day at 1 pm
jobs:
  build:
    runs-on: macos-11
    steps:
      - name: Check out realm repo
        uses: actions/checkout@v2
        with:
          path: main

      - name: Check out realm repo
        uses: actions/checkout@v2
        with:
          repository: realm/realm-cocoa
          path: realm

      - name: Get master realm verion
        id: rVer
        run: |
           echo "::set-output name=realm_version::$(./realm/build.sh get-version)"

      - name: Getting latest binares version
        id: realmPrebuildR
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          repository: pcpl2/RealmPrebuild
          excludes: prerelease, draft

#TODO if release has changed
      - if: steps.realmPrebuildR.outputs.release != steps.rVer.outputs.realm_version
        name: Build Realm
        env: 
          - REALM_XCODE_VERSION: 13.0
        run: |
          ./build.sh xcframework ios

      - if: steps.realmPrebuildR.outputs.release != steps.rVer.outputs.realm_version
        name: Make Realm.xcframework.zip file
        uses: papeloto/action-zip@v1
        with:
          files: ./realm/build/ios/swift-13.0
          dest: Realm.xcframework.zip

      - uses: actions/upload-artifact@v2
        with:
          name: Realm.xcframework.zip
          path: Realm.xcframework.zip
          retention-days: 1
      
#      - if: steps.realmPrebuildR.outputs.release != steps.rVer.outputs.realm_version
#        name: Calculate SHA of files
#        id: xcframeworkSha
#        run: | 
#          cd realm/build/ios/swift-13.0
#          echo "::set-output name=realm_version::$(Realm.xcframework)"
#          echo "::set-output name=realm_version::$(RealmSwift.xcframework)"

# shasum -a 256 file.zip generate sha for Package.swift
    #- uses: actions/checkout@v2
    #- uses: timbertson/self-update-action@v1
    #  with:
    #    GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
    #    updateScript: "./update.sh"